// Customers
export const FETCH_CUSTOMERS = 'Fetch successfully'
export const FETCH_CUSTOMERS_ERR = 'Fetch error'
export const FETCH_CUSTOMER = 'Fetch index successfully'
export const FETCH_CUSTOMER_ERR = 'Fetch index error'
export const STORE_CUSTOMERS = 'Store successfully'
export const UPDATE_CUSTOMERS = 'Update successfully'
export const DESTROY_CUSTOMERS = 'Destroy successfully'
// Products
export const FETCH_PRODUCTS = 'Fetch successfully'
export const FETCH_PRODUCTS_ERR = 'Fetch error'
export const FETCH_PRODUCT = 'Fetch index successfully'
export const FETCH_PRODUCT_ERR = 'Fetch index error'
export const STORE_PRODUCTS = 'Store successfully'
export const UPDATE_PRODUCTS = 'Update successfully'
export const DESTROY_PRODUCTS = 'Destroy successfully'