// Customers
export const FETCH_CUSTOMERS = 'Fetch Customers successfully'
export const FETCH_CUSTOMERS_ERR = 'Fetch Customers error'
export const FETCH_CUSTOMER = 'Fetch Customers index successfully'
export const FETCH_CUSTOMER_ERR = 'Fetch Customers index error'
export const STORE_CUSTOMERS = 'Store Customers successfully'
export const UPDATE_CUSTOMERS = 'Update Customers successfully'
export const DESTROY_CUSTOMERS = 'Destroy Customers successfully'
// Products
export const FETCH_PRODUCTS = 'Fetch Products successfully'
export const FETCH_PRODUCTS_ERR = 'Fetch Products error'
export const FETCH_PRODUCT = 'Fetch Products index successfully'
export const FETCH_PRODUCT_ERR = 'Fetch Products index error'
export const STORE_PRODUCTS = 'Store Products successfully'
export const UPDATE_PRODUCTS = 'Update Products successfully'
export const DESTROY_PRODUCTS = 'Destroy Products successfully'
// Offices
export const FETCH_OFFICES = 'Fetch Offices successfully'
export const FETCH_OFFICES_ERR = 'Fetch Offices error'
export const FETCH_OFFICE = 'Fetch Offices index successfully'
export const FETCH_OFFICE_ERR = 'Fetch Offices index error'
export const STORE_OFFICES = 'Store Offices successfully'
export const UPDATE_OFFICES = 'Update Offices successfully'
export const DESTROY_OFFICES = 'Destroy Offices successfully'
// Invoice
export const FETCH_INVOICES = 'Fetch Invoice successfully'
export const FETCH_INVOICES_ERR = 'Fetch Invoice error'
export const FETCH_INVOICE = 'Fetch Invoice index successfully'
export const FETCH_INVOICE_ERR = 'Fetch Invoice index error'
export const STORE_INVOICES = 'Store Invoice successfully'
export const UPDATE_INVOICES = 'Update Invoice successfully'
export const DESTROY_INVOICES = 'Destroy Invoice successfully'
// FiscalCredits
export const FETCH_FISCALCREDITS = 'Fetch FiscalCredits successfully'
export const FETCH_FISCALCREDITS_ERR = 'Fetch FiscalCredits error'
export const FETCH_FISCALCREDIT = 'Fetch FiscalCredits index successfully'
export const FETCH_FISCALCREDIT_ERR = 'Fetch FiscalCredits index error'
export const STORE_FISCALCREDITS = 'Store FiscalCredits successfully'
export const UPDATE_FISCALCREDITS = 'Update FiscalCredits successfully'
export const DESTROY_FISCALCREDITS = 'Destroy FiscalCredits successfully'
// Quotes
export const FETCH_QUOTES = 'Fetch Quotes successfully'
export const FETCH_QUOTES_ERR = 'Fetch Quotes error'
export const FETCH_QUOTE = 'Fetch Quotes index successfully'
export const FETCH_QUOTE_ERR = 'Fetch Quotes index error'
export const STORE_QUOTES = 'Store Quotes successfully'
export const UPDATE_QUOTES = 'Update Quotes successfully'
export const DESTROY_QUOTES = 'Destroy Quotes successfully'

// Suppliers
export const FETCH_SUPPLIERS = 'Fetch Suppliers successfully'
export const FETCH_SUPPLIERS_ERR = 'Fetch Suppliers error'
export const FETCH_SUPPLIER = 'Fetch Suppliers index successfully'
export const FETCH_SUPPLIER_ERR = 'Fetch Suppliers index error'
export const STORE_SUPPLIERS = 'Store Suppliers successfully'
export const UPDATE_SUPPLIERS = 'Update Suppliers successfully'
export const DESTROY_SUPPLIERS = 'Destroy Suppliers successfully'