// Customers
export const FETCH_CUSTOMERS = 'Fetch Customers successfully'
export const FETCH_CUSTOMERS_ERR = 'Fetch Customers error'
export const FETCH_CUSTOMER = 'Fetch Customers index successfully'
export const FETCH_CUSTOMER_ERR = 'Fetch Customers index error'
export const STORE_CUSTOMERS = 'Store Customers successfully'
export const UPDATE_CUSTOMERS = 'Update Customers successfully'
export const DESTROY_CUSTOMERS = 'Destroy Customers successfully'
// Products
export const FETCH_PRODUCTS = 'Fetch Products successfully'
export const FETCH_PRODUCTS_ERR = 'Fetch Products error'
export const FETCH_PRODUCT = 'Fetch Products index successfully'
export const FETCH_PRODUCT_ERR = 'Fetch Products index error'
export const STORE_PRODUCTS = 'Store Products successfully'
export const UPDATE_PRODUCTS = 'Update Products successfully'
export const DESTROY_PRODUCTS = 'Destroy Products successfully'
// Offices
export const FETCH_OFFICES = 'Fetch Offices successfully'
export const FETCH_OFFICES_ERR = 'Fetch Offices error'
export const FETCH_OFFICE = 'Fetch Offices index successfully'
export const FETCH_OFFICE_ERR = 'Fetch Offices index error'
export const STORE_OFFICES = 'Store Offices successfully'
export const UPDATE_OFFICES = 'Update Offices successfully'
export const DESTROY_OFFICES = 'Destroy Offices successfully'